version: '3.9'

services:
  postgres:
    image: ankane/pgvector
    container_name: mem0-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mem0:
    image: mcp/mem0
    env_file: .env
    ports:
      - "8050:8050"
    depends_on:
      - postgres

volumes:
  postgres_data:
