
apiVersion: v1
kind: Service
metadata:
  name: api-fast-docker
spec:
  selector:
    app: api-fast-docker
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

