apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mcp-server
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: mcp-server
          port: {{ .Values.service.port }}

